# Spring Boot configuration
spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/etica_db
    username: postgres
    password: 123
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  # Configuración de Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/   # Ruta donde se encuentran las plantillas
    suffix: .html                   # Extensión de los archivos de plantillas
    encoding: UTF-8                 # Codificación de caracteres
    content-type: text/html         # Tipo de contenido
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port
